# Generated by Django 5.2.1 on 2025-10-18 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passenger_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Passenger ID",
                    ),
                ),
                (
                    "naid",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="NAID"
                    ),
                ),
                (
                    "ship_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ship name"
                    ),
                ),
                (
                    "departure_port",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="depature port",
                    ),
                ),
                (
                    "arrival_port",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="arrival port",
                    ),
                ),
                (
                    "arrival_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="arrival date"
                    ),
                ),
                (
                    "passenger_class",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="class"
                    ),
                ),
                (
                    "image_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="image #"
                    ),
                ),
                (
                    "line_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="line #"
                    ),
                ),
                (
                    "name_individual",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="individual"
                    ),
                ),
                (
                    "name_family",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="family"
                    ),
                ),
                (
                    "name_tribal",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="tribal"
                    ),
                ),
                (
                    "chinese_signature",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Chinese signature",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="sex"
                    ),
                ),
                (
                    "pob_city_chinese",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Chinese standardized city/village",
                    ),
                ),
                (
                    "pob_city_std",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="standardized city/village",
                    ),
                ),
                (
                    "pob_city_raw",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="city/village",
                    ),
                ),
                (
                    "pob_district_chinese",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Chinese standardized district",
                    ),
                ),
                (
                    "pob_district_std",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="standardized district",
                    ),
                ),
                (
                    "pob_district_raw",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="district"
                    ),
                ),
                (
                    "pob_country",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="country"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth (parsed)"
                    ),
                ),
                (
                    "date_of_birth_raw",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="date of birth (raw text)",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="destination",
                    ),
                ),
                (
                    "physical_markers",
                    models.TextField(
                        blank=True, null=True, verbose_name="physical markers"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MerchantInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered_cert_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="If registered, number of certificate of residence",
                    ),
                ),
                (
                    "return_date_china",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Return to China"
                    ),
                ),
                (
                    "steamship_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Name of steamship on which returned to China",
                    ),
                ),
                (
                    "firm_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Of what firm a member",
                    ),
                ),
                (
                    "firm_address",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Location of firm (address)",
                    ),
                ),
                (
                    "firm_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Location of firm (city)",
                    ),
                ),
                (
                    "members_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="# members"
                    ),
                ),
                (
                    "years_member",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="How long a member of firm",
                    ),
                ),
                (
                    "capital_invested",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount of interest in firm",
                    ),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_info",
                        to="records.passenger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LaborerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cert_residence_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Number of certificate of residence",
                    ),
                ),
                (
                    "return_cert_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Number of return certificate",
                    ),
                ),
                (
                    "us_residence_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Place of residence in United States (City)",
                    ),
                ),
                (
                    "us_residence_state",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Place of residence in United States (State)",
                    ),
                ),
                (
                    "departure_port_us",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Port of departure from United States",
                    ),
                ),
                (
                    "departure_date_us",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date of Departure From United States",
                    ),
                ),
                (
                    "claim_basis",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Basis of Claim to Readmission",
                    ),
                ),
                (
                    "overtime_certificate",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Overtime certificate (consul report)",
                    ),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laborer_info",
                        to="records.passenger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExemptInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "official_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Official title / Charter of certificate",
                    ),
                ),
                (
                    "last_occupation",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Last Occupation And Where Pursued",
                    ),
                ),
                (
                    "occupation_place",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Where pursued (occupation)",
                    ),
                ),
                (
                    "intended_occupation",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Intended Occupation In The United States",
                    ),
                ),
                (
                    "intended_residence",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Intended Place Of Residence In The United States",
                    ),
                ),
                (
                    "intended_duration",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="How Long Proposes To Remain In The United States",
                    ),
                ),
                (
                    "study_subject",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="What Study To Be Pursued",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Name Of School Or College Intends To Enter",
                    ),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exempt_info",
                        to="records.passenger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransitInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cause_departure",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Cause of departure from United States",
                    ),
                ),
                (
                    "us_residence",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Residence while in United States",
                    ),
                ),
                (
                    "us_occupation",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Occupation while in United States",
                    ),
                ),
                (
                    "registered",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Whether registered",
                    ),
                ),
                (
                    "registration_cert_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Number of registration certification",
                    ),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transit_info",
                        to="records.passenger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WifeChildInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "husband_or_father",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Name of husband or father",
                    ),
                ),
                (
                    "residence_husband_father_address",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Residence of husband or father (address)",
                    ),
                ),
                (
                    "residence_husband_father_state",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Residence of husband or father (state)",
                    ),
                ),
                (
                    "witnesses",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Names and residences of persons cognizant of facts",
                    ),
                ),
                (
                    "marriage_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of marriage"
                    ),
                ),
                (
                    "marriage_place",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Place of marriage",
                    ),
                ),
                (
                    "children_names",
                    models.TextField(
                        blank=True, null=True, verbose_name="Name of Children"
                    ),
                ),
                (
                    "first_and_only_wife",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Whether first and only living wife",
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Name of mother",
                    ),
                ),
                (
                    "brothers_names",
                    models.TextField(
                        blank=True, null=True, verbose_name="Names of brothers"
                    ),
                ),
                (
                    "sisters_names",
                    models.TextField(
                        blank=True, null=True, verbose_name="Names of sisters"
                    ),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wifechild_info",
                        to="records.passenger",
                    ),
                ),
            ],
        ),
    ]
