# Generated by Django 5.2.7 on 2025-10-10 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naid", models.CharField(blank=True, max_length=50, null=True)),
                ("ship_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "departure_port",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "arrival_port",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("arrival_date", models.DateField(blank=True, null=True)),
                (
                    "passenger_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("image_no", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("sex", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("physical_markers", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MerchantInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cert_residence_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("return_date_china", models.DateField(blank=True, null=True)),
                (
                    "steamship_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("firm_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "firm_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("firm_city", models.CharField(blank=True, max_length=100, null=True)),
                ("members_count", models.IntegerField(blank=True, null=True)),
                (
                    "years_member",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "capital_invested",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_info",
                        to="records.passenger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LaborerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cert_residence_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "return_cert_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "us_residence_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "departure_port_us",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("departure_date_us", models.DateField(blank=True, null=True)),
                ("claim_basis", models.TextField(blank=True, null=True)),
                (
                    "overtime_certificate",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laborer_info",
                        to="records.passenger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExemptInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "official_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "last_occupation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "occupation_place",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "intended_occupation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "intended_residence",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "intended_duration",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "student_study",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "student_school",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exempt_info",
                        to="records.passenger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransitInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ever_resided_us",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cause_departure", models.TextField(blank=True, null=True)),
                (
                    "us_residence",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "us_occupation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("registered", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "registration_cert_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transit_info",
                        to="records.passenger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WifeChildInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "husband_or_father",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "residence_husband_father",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("witnesses", models.TextField(blank=True, null=True)),
                ("marriage_date", models.DateField(blank=True, null=True)),
                (
                    "marriage_place",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("children_names", models.TextField(blank=True, null=True)),
                (
                    "first_and_only_wife",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("siblings_names", models.TextField(blank=True, null=True)),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wifechild_info",
                        to="records.passenger",
                    ),
                ),
            ],
        ),
    ]
