# Generated by Django 5.2.7 on 2025-10-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laborerinfo",
            name="passenger",
        ),
        migrations.RemoveField(
            model_name="merchantinfo",
            name="passenger",
        ),
        migrations.RemoveField(
            model_name="transitinfo",
            name="passenger",
        ),
        migrations.RemoveField(
            model_name="wifechildinfo",
            name="passenger",
        ),
        migrations.RemoveField(
            model_name="passenger",
            name="name",
        ),
        migrations.RemoveField(
            model_name="passenger",
            name="place_of_birth",
        ),
        migrations.AddField(
            model_name="passenger",
            name="chinese_signature",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="line_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="name_family",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="name_individual",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="name_tribal",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="pob_city_chinese",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="pob_city_raw",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="pob_city_std",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="pob_country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="pob_district_chinese",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="pob_district_raw",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="pob_district_std",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="ExemptInfo",
        ),
        migrations.DeleteModel(
            name="LaborerInfo",
        ),
        migrations.DeleteModel(
            name="MerchantInfo",
        ),
        migrations.DeleteModel(
            name="TransitInfo",
        ),
        migrations.DeleteModel(
            name="WifeChildInfo",
        ),
    ]
