# Generated by Django 5.2.7 on 2025-10-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_exemptinfo_laborerinfo_merchantinfo_transitinfo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitinfo",
            name="ever_resided_us",
        ),
        migrations.RemoveField(
            model_name="wifechildinfo",
            name="residence_husband_father",
        ),
        migrations.AddField(
            model_name="wifechildinfo",
            name="residence_husband_father_address",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Residence of husband or father (address)",
            ),
        ),
        migrations.AddField(
            model_name="wifechildinfo",
            name="residence_husband_father_state",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Residence of husband or father (state)",
            ),
        ),
        migrations.AlterField(
            model_name="exemptinfo",
            name="intended_duration",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="How Long Proposes To Remain In The United States",
            ),
        ),
        migrations.AlterField(
            model_name="exemptinfo",
            name="intended_occupation",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Intended Occupation In The United States",
            ),
        ),
        migrations.AlterField(
            model_name="exemptinfo",
            name="intended_residence",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Intended Place Of Residence In The United States",
            ),
        ),
        migrations.AlterField(
            model_name="exemptinfo",
            name="last_occupation",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Last Occupation And Where Pursued",
            ),
        ),
        migrations.AlterField(
            model_name="exemptinfo",
            name="occupation_place",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Where pursued (occupation)",
            ),
        ),
        migrations.AlterField(
            model_name="exemptinfo",
            name="official_title",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Official title / Charter of certificate",
            ),
        ),
        migrations.AlterField(
            model_name="exemptinfo",
            name="school_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Name Of School Or College Intends To Enter",
            ),
        ),
        migrations.AlterField(
            model_name="exemptinfo",
            name="study_subject",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="What Study To Be Pursued",
            ),
        ),
        migrations.AlterField(
            model_name="laborerinfo",
            name="cert_residence_no",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Number of certificate of residence",
            ),
        ),
        migrations.AlterField(
            model_name="laborerinfo",
            name="claim_basis",
            field=models.TextField(
                blank=True, null=True, verbose_name="Basis of Claim to Readmission"
            ),
        ),
        migrations.AlterField(
            model_name="laborerinfo",
            name="departure_date_us",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date of Departure From United States",
            ),
        ),
        migrations.AlterField(
            model_name="laborerinfo",
            name="departure_port_us",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Port of departure from United States",
            ),
        ),
        migrations.AlterField(
            model_name="laborerinfo",
            name="overtime_certificate",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Overtime certificate (consul report)",
            ),
        ),
        migrations.AlterField(
            model_name="laborerinfo",
            name="return_cert_no",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Number of return certificate",
            ),
        ),
        migrations.AlterField(
            model_name="laborerinfo",
            name="us_residence_city",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Place of residence in United States (City)",
            ),
        ),
        migrations.AlterField(
            model_name="laborerinfo",
            name="us_residence_state",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Place of residence in United States (State)",
            ),
        ),
        migrations.AlterField(
            model_name="merchantinfo",
            name="capital_invested",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Amount of interest in firm",
            ),
        ),
        migrations.AlterField(
            model_name="merchantinfo",
            name="firm_address",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Location of firm (address)",
            ),
        ),
        migrations.AlterField(
            model_name="merchantinfo",
            name="firm_city",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Location of firm (city)",
            ),
        ),
        migrations.AlterField(
            model_name="merchantinfo",
            name="firm_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Of what firm a member",
            ),
        ),
        migrations.AlterField(
            model_name="merchantinfo",
            name="members_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="# members"),
        ),
        migrations.AlterField(
            model_name="merchantinfo",
            name="registered_cert_no",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="If registered, number of certificate of residence",
            ),
        ),
        migrations.AlterField(
            model_name="merchantinfo",
            name="return_date_china",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date of Return to China"
            ),
        ),
        migrations.AlterField(
            model_name="merchantinfo",
            name="steamship_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Name of steamship on which returned to China",
            ),
        ),
        migrations.AlterField(
            model_name="merchantinfo",
            name="years_member",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="How long a member of firm",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="arrival_date",
            field=models.DateField(blank=True, null=True, verbose_name="arrival date"),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="arrival_port",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="arrival port"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="chinese_signature",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Chinese signature"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="departure_port",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="depature port"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="destination",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="destination"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="image_no",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="image #"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="line_no",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="line #"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="naid",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="NAID"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="name_family",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="family"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="name_individual",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="individual"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="name_tribal",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="tribal"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="passenger_class",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="class"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="physical_markers",
            field=models.TextField(
                blank=True, null=True, verbose_name="physical markers"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="pob_city_chinese",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Chinese standardized city/village",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="pob_city_raw",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="city/village"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="pob_city_std",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="standardized city/village",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="pob_country",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="pob_district_chinese",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Chinese standardized district",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="pob_district_raw",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="district"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="pob_district_std",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="standardized district",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="sex",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="sex"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="ship_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ship name"
            ),
        ),
        migrations.AlterField(
            model_name="transitinfo",
            name="cause_departure",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Cause of departure from United States",
            ),
        ),
        migrations.AlterField(
            model_name="transitinfo",
            name="registered",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Whether registered"
            ),
        ),
        migrations.AlterField(
            model_name="transitinfo",
            name="registration_cert_no",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Number of registration certification",
            ),
        ),
        migrations.AlterField(
            model_name="transitinfo",
            name="us_occupation",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Occupation while in United States",
            ),
        ),
        migrations.AlterField(
            model_name="transitinfo",
            name="us_residence",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Residence while in United States",
            ),
        ),
        migrations.AlterField(
            model_name="wifechildinfo",
            name="brothers_names",
            field=models.TextField(
                blank=True, null=True, verbose_name="Names of brothers"
            ),
        ),
        migrations.AlterField(
            model_name="wifechildinfo",
            name="children_names",
            field=models.TextField(
                blank=True, null=True, verbose_name="Name of Children"
            ),
        ),
        migrations.AlterField(
            model_name="wifechildinfo",
            name="first_and_only_wife",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Whether first and only living wife",
            ),
        ),
        migrations.AlterField(
            model_name="wifechildinfo",
            name="husband_or_father",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Name of husband or father",
            ),
        ),
        migrations.AlterField(
            model_name="wifechildinfo",
            name="marriage_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date of marriage"
            ),
        ),
        migrations.AlterField(
            model_name="wifechildinfo",
            name="marriage_place",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Place of marriage"
            ),
        ),
        migrations.AlterField(
            model_name="wifechildinfo",
            name="mother_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Name of mother"
            ),
        ),
        migrations.AlterField(
            model_name="wifechildinfo",
            name="sisters_names",
            field=models.TextField(
                blank=True, null=True, verbose_name="Names of sisters"
            ),
        ),
        migrations.AlterField(
            model_name="wifechildinfo",
            name="witnesses",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Names and residences of persons cognizant of facts",
            ),
        ),
    ]
