# Generated by Django 5.2.7 on 2025-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_remove_transitinfo_ever_resided_us_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="date_of_birth_raw",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="date of birth (raw text)",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="date of birth (parsed)"
            ),
        ),
    ]
